### ISSUE TITLE
opam 2.0 can't be built on Cygwin64

### ISSUE THREAD

**Issue by yannl35133** [ocaml/opam#3503]
I have tried different methods of installing opam (the Windows WIP guide, `make cold`, the full archive on [the opam website](https://opam.ocaml.org/2.0-preview/doc/Install.html), none of which worked for me, and each causing different errors.
I am new to opam, and the only thing I want is to get merlin and its code styling, please let me know how to get it.
If you want error reports, ask me what exactly to put in them.

**Comment by AltGr** [comment]
Windows support is still pretty much work in progress, but @dra27 has been doing tremendous work, part of which has been merged into opam 2.0.0, and we are soon getting there!

I'll let him elaborate :)

**Comment by dra27** [comment]
opam 2.0.0 should be working in Cygwin, yes - that's as in compiled with Cygwin's gcc, not any of the native ports of OCaml (mingw-w64 or MSVC).

Are you using 32-bit Cygwin or 64-bit Cygwin? 64-bit Cygwin is completely broken for OCaml at the moment, I'm afraid.

**Comment by yannl35133** [comment]
I am using 64-bit Cygwin, and most of my tries were with mingw, so I guess this answers my problems. I am only using Cygwin for opam and OCaml, so I am going to retry with 32-bit Cygwin right now.
Thank you very much, I'll tell you if it worked with 32-bit Cygwin

**Comment by yannl35133** [comment]
It worked out, I got no problems, perfect.
So maybe you should put it somewhere in 'README.md' that opam (2.0.0) does not work yet with 64-bit Cygwin.
Anyway, thanks a lot.

PS: Should I close the issue now, even though my problems are still there ?

**Comment by dra27** [comment]
Good, glad it's working on Cygwin32!

Up to @rjbou where to record the Cygwin64 issue - opam itself is not broken, the issue is that you can't build OCaml. I realise that that distinction is of limited comfort when your end goal is simply being able to use opam, but my point is that there's nothing that would be fixed in opam, other than bumping the version of OCaml built in `make cold`.

For me, this issue could sensibly be renamed "opam 2.0 can't be built on Cygwin64" and left open to track this?

**Comment by rjbou** [comment]
Updated related readme documentation, and yes, better keep the issue open like that it is can be more easily found.
Thanks for reporting!

**Comment by mclagett** [comment]
I'm experiencing fork issues when trying to install Opam on cygwin running on windows 10.  Here's the error:  

      0 [main] ocamlrun 1563 child_info_fork::abort: address space needed by 'dllunix.so' (0x400000) is already occupied
Error: fork: : Resource temporarily unavailable
make: *** [Makefile:30: src_ext/dune-local/_build/install/default/bin/dune] Error 1

I understand this is a fairly common cygwin issue, but I'm wondering if anyone here has any ideas for me.  I have been trying to build Bucklescript and need OPam to be able to switch to the vendor supplied OCaml version (using the following suggested command):

opam switch reinstall 4.02.3+buckle-master

But every time I have tried to build Opam I get the error above.  I've uninstalled and reinstalled Cygwin.  I've rebooted.  I've tried rebasing (via the setup program and autorebase).  Do any of you old hands have any ideas for me.

**Comment by yannl35133** [comment]
This issue should probably be closed, as OPAM can now be built through Cygwin setup.
Though I still experience fork issues, as referenced by @mclagett , in #3785 and in #3953 which prevent me from installing dune, and I am very interested in a fix for this.

**Comment by rjbou** [comment]
Closing then, feel free to reopen if needed.
Thanks!
