### ISSUE TITLE
Even though I'm using M1 mac, `opam config report` outputs arch=x86_64

### ISSUE THREAD

**Issue by ose20** [ocaml/opam#4798]
I use M1 mac.

```
$ uname -m
arm64
```

But `opam config report` says that my architecture is x86_64
```
$ opam config report
# opam config report
# opam-version      2.0.8
# self-upgrade      no
# system            arch=x86_64 os=macos os-distribution=homebrew os-version=11.3.1
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              7
# repositories      1 (http) (default repo at b00f2272)
# pinned            0
# current-switch    4.11.1+BER
```

So, why arch isn't "arm64" ?

**Comment by kit-ty-kate** [comment]
I'm not able to reproduce this on my M1 mac. Could you give us the result of `file $(which opam)`? If it is an arm64 binary it should give you:
```
/usr/local/bin/opam: Mach-O 64-bit executable arm64
```
* If it tells you x86_64 then you just need to upgrade opam (brew has the correct version)
* If it is from brew, then which version of brew did you install?
* If not, in which terminal emulator do you run things?

In any case I would suspect a call to `arch -x86_64 <cmd>` is used somewhere down the line. I know some people have been running their terminal emulator using Rosetta and getting the x86_64 version of everything instead of the native one.

**Comment by ose20** [comment]
Thank you for responding.

In my environment, 
```
$ file $(which opam)
/opt/homebrew/bin/opam: Mach-O 64-bit executable x86_64
```

> If it tells you x86_64 then you just need to upgrade opam (brew has the correct version)

So, I followed your next instructions and did the following command
```
$ opam upgrade
Everything as up-to-date as possible (run with --verbose to show unavailable upgrades).

The following packages are not being upgraded because the new versions conflict with other installed packages:
  - merlin.4.2-412
  - ocaml-lsp-server.1.7.0
However, you may "opam upgrade" these packages explicitly, which will ask permission to downgrade or uninstall the conflicting
packages.
Nothing to do.
```

Does this message mean that I can't upgrade opam ?

> If it is from brew, then which version of brew did you install?

Yes. I installed opam from brew. But Unfortunately I can't remember which version of brew I used then.
I don't know if this will help you, but I share the present version.

```
$ brew config
HOMEBREW_VERSION: 3.2.5
...
(omit)
...
macOS: 11.3.1-arm64
...
Rosetta 2: false
```

> If not, in which terminal emulator do you run things?

I'll answer this question as well, just in case.
I use iTerm and I don't use Rosetta in this terminal.

**Comment by kit-ty-kate** [comment]
Ah sorry I wasn't clear enough. When I said upgrade opam I meant:
```
brew upgrade opam
```
`opam upgrade` means "upgrade the packages installed by opam".

Here is what I got via brew:
```
 % brew install opam
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from ea7540be8 to c5de106c2.
Updated 4 taps (homebrew/core, homebrew/cask, homebrew/cask-fonts and homebrew/services).
==> New Formulae
apt                                                firefoxpwa                                         pari-elldata                                       xsel
==> Updated Formulae
Updated 135 formulae.
==> New Casks
betterdiscord-installer                                             midi-router-client                                                  vym
==> Updated Casks
Updated 164 casks.
==> Deleted Casks
3cxphone                                                            baiducloud                                                          superbeam

==> Downloading https://ghcr.io/v2/homebrew/core/gpatch/manifests/2.7.6
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/gpatch/blobs/sha256:c90e7baee17d21e0cb594db676912e108f7df68b71509e15d37edfadcd6b12e9
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:c90e7baee17d21e0cb594db676912e108f7df68b71509e15d37edfadcd6b12e9?se=2021-08-12T20%3A15%3A00Z&sig=O229WZ6PP20czFB4SRCglS
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/opam/manifests/2.1.0
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/opam/blobs/sha256:123479f1d339a12438b69a3989fe7a071afb27199e0fc43c03dd48a931a16d87
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:123479f1d339a12438b69a3989fe7a071afb27199e0fc43c03dd48a931a16d87?se=2021-08-12T20%3A15%3A00Z&sig=%2FOt7dOvsr7oAvFTkgy1X
######################################################################## 100.0%
==> Installing dependencies for opam: gpatch
==> Installing opam dependency: gpatch
==> Pouring gpatch--2.7.6.arm64_big_sur.bottle.tar.gz
🍺  /opt/homebrew/Cellar/gpatch/2.7.6: 10 files, 351.9KB
==> Installing opam
==> Pouring opam--2.1.0.arm64_big_sur.bottle.tar.gz
==> Caveats
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions
==> Summary
🍺  /opt/homebrew/Cellar/opam/2.1.0: 50 files, 13.4MB
==> Caveats
==> opam
OPAM uses ~/.opam by default for its package database, so you need to [....]
% file /opt/homebrew/bin/opam
/opt/homebrew/bin/opam: Mach-O 64-bit executable arm64
```
Once reinstalled your issue should be fixed.

**Comment by ose20** [comment]
I'm sorry. I misunderstood.

Going straight to the point, I was able to solve the problem, thank you !

To be more specific, there were several steps to the solution.
Here, I upgraded opam via brew, but some problem still seemed to occur.

```
$ brew upgrade opam
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
apt                  docuum               firefoxpwa           pari-elldata         stylua               xsel
bupstash             fanyi                i2c-tools            rsc_2fa              wildmidi
==> Updated Formulae
Updated 835 formulae.
==> Deleted Formulae
terraform-provisioner-ansible                                    tj

==> Upgrading 1 outdated package:
opam 2.0.8 -> 2.1.0
==> Upgrading opam
  2.0.8 -> 2.1.0

==> Downloading https://ghcr.io/v2/homebrew/core/opam/manifests/2.1.0
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/opam/blobs/sha256:123479f1d339a12438b69a3989fe7a071afb27199e0fc43c03dd48a931a16
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:123479f1d339a12438b69a3989fe7a071afb27199e0
######################################################################## 100.0%
==> Pouring opam--2.1.0.arm64_big_sur.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /opt/homebrew
Could not symlink bin/opam
Target /opt/homebrew/bin/opam
already exists. You may want to remove it:
  rm '/opt/homebrew/bin/opam'

To force the link and overwrite all conflicting files:
  brew link --overwrite opam

To list all files that would be deleted:
  brew link --overwrite --dry-run opam

Possible conflicting files are:
/opt/homebrew/bin/opam
==> Caveats
OPAM uses ~/.opam by default for its package database, so you need to
initialize it first by running:

$ opam init

Bash completion has been installed to:
  /opt/homebrew/etc/bash_completion.d
==> Summary
🍺  /opt/homebrew/Cellar/opam/2.1.0: 50 files, 13.4MB
Removing: /opt/homebrew/Cellar/opam/2.0.8... (48 files, 11.5MB)
Removing: /Users/[...]/Library/Caches/Homebrew/opam--2.0.8... (3.9MB)
```

So, following this message about `brew link` command, 
```
$ rm /opt/homebrew/bin/opam
/opt/homebrew/bin/opam
```
and
```
$ brew link opam
Linking /opt/homebrew/Cellar/opam/2.1.0... 44 symlinks created.
```
finally,  I got
```
$ file /opt/homebrew/bin/opam
/opt/homebrew/bin/opam: Mach-O 64-bit executable arm64
```

`opam config report` also tells that my arch is arm64 !

Thank you for your support, It was very helpful.
