### ISSUE TITLE
Opam resolution issue on `mips64el` architecture

### ISSUE THREAD

**Issue by WardBrian** [ocaml/opam#5697]
While attempting to install `core.v0.16.0`, I receive the following error:
` Sorry, no solution found: there seems to be a problem with your request.`

I originally reported this at https://github.com/janestreet/core/issues/167 but was asked to report here instead.

I've been able to install this same environment on other architectures such as s390x, armhf, armel, ppc64le, and amd64. 
The following dockerfile is where the issue first came to my attention, but I have also recreated it manually: https://github.com/stan-dev/ci-scripts/blob/ee6d8d589c0556b1182ea5bea367d6c958cff910/docker/stanc3/multiarch/Dockerfile

Opam config report:
```
# opam config report
# opam-version      2.0.3 
# self-upgrade      no
# system            arch=mips64 os=linux os-distribution=debian os-version=10
# solver            mccs
# install-criteria  -removed,-count[version-lag:,true],-changed,-count[version-lag:,false],-new
# upgrade-criteria  -removed,-count[version-lag:,false],-new
# jobs              7
# repositories      1 (http) (default repo at a6d21a4b)
# pinned            0
# current-switch    4.14.1
```

**Comment by kit-ty-kate** [comment]
The underlying problem is that `num` is not compatible with `ocaml-option-bytecode-only` and it is required to install core (via sexplib)
```
OPAMVAR_arch=mips64 opam reinstall --show core.v0.16.0 ocaml.4.14.1 ocaml-option-bytecode-only
core.v0.16.0, ocaml.4.14.1 and ocaml-option-bytecode-only are not installed. Install them? [Y/n] y
The following dependencies couldn't be met:
  - core → sexplib >= v0.16 → num → ocaml < 4.06.0
Your request can't be satisfied:
  - No available version of ocaml satisfies the constraints
  - num >= 1.0 is in conflict with ocaml-option-bytecode-only

No solution found, exiting
```

Now the fact that opam doesn’t give you a proper reason is a known bug fixed in https://github.com/ocaml/opam/pull/5263 (released as 2.1.5).
The version of opam that you have is almost 5 years old, could you try with an up-to-date version?

If your distribution is too old and does not have an up-to-date opam you can install the latest release of opam using:
```
bash -c "sh <(curl -fsSL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)"

**Comment by WardBrian** [comment]
That yields 

```
## Downloading opam 2.1.5 for linux on mips64...
Checksum mismatch, a problem occurred during download.
```

Which I'm guessing is because opam doesn't seem to have binaries available for `mips64el`.

Honestly, though, being able to determine that `num` was the issue is already very helpful, thank you! It looks like https://github.com/ocaml/num/pull/30 fixed this, but has not been released.

I can go ask them nicely :)

**Comment by WardBrian** [comment]
`make cold` fails (due to a lack of native code compiler, I'm assuming there's some configure flag I could pass that would make this work?)

However, pinning `num` to the version currently on github appears to resolve the issue. Thank you for your help!

**Comment by barracuda156** [comment]
@WardBrian `ocaml-num` was compiling with my fix as bytecode-only, but apparently it is still broken in 1.5 in the master, and I need to adapt the patch, since it no longer applies as-is.

P. S. `ppc` is also bytecode-only.
